[package]
name = "pitr_util"
version = "0.1.0"
authors = ["urlordjames <32751441+urlordjames@users.noreply.github.com>"]
license = "MIT"
edition = "2018"

[dependencies]
serde_json = "1"
serde = { version = "1", features = [ "derive" ] }

[profiles.release]
lto = "fat"
